version: "3.3"
services:

  postgres-dev:
    build:
      context: .
      dockerfile: docker-database.Dockerfile
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  backend-dev:
    build:
      context: .
      dockerfile: docker-backend.Dockerfile
    depends_on:
      - postgres-dev
    environment:
      DB_CONNECTION_STRING: postgres://user:pass@postgres-dev:5432/db
      NODE_ENV: development
      PORT: 3005
      DEFAULT_COUNTRY_ID: gbr
    ports:
      - "5205:3005"
    command: yarn backend:dev
    volumes:
      - ./packages/backend:/usr/app/packages/backend/
      - /usr/app/packages/backend/node_modules
      - ./packages/shared-models:/usr/app/packages/shared-models/
      - /usr/app/packages/shared-models/node_modules

  frontend-dev:
    build:
      context: .
      dockerfile: docker-frontend.Dockerfile
    depends_on:
      - backend-dev
    environment:
      BACKEND_URL: http://localhost:5205/v2
    ports:
      - "5200:3000"
    command: yarn frontend:dev
    volumes:
      - ./packages/frontend:/usr/app/packages/frontend/
      - /usr/app/packages/frontend/node_modules
      - ./packages/shared-models:/usr/app/packages/shared-models/
      - /usr/app/packages/shared-models/node_modules
      - ./packages/shared-frontend-components:/usr/app/packages/shared-frontend-components/
      - /usr/app/packages/shared-frontend-components/node_modules
      - ./packages/shared-frontend-utilities:/usr/app/packages/shared-frontend-utilities/
      - /usr/app/packages/shared-frontend-utilities/node_modules
