# Override of docker-compose.test.yml

version: "3.3"
services:

  postgres-test:
    volumes:
      - ./packages/database/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  backend-test:
    command: yarn workspace @chrisb-dev/seasonal-backend test
    environment:
      IS_CI: "false"
    volumes:
      - ./packages/backend:/usr/app/packages/backend
      - /usr/app/packages/backend/node_modules

  frontend-test:
    volumes:
      - ./packages/frontend:/usr/app/packages/frontend/
      - /usr/app/packages/frontend/node_modules
      - ./packages/shared-models:/usr/app/packages/shared-models/
      - /usr/app/packages/shared-models/node_modules
      - ./packages/shared-frontend-components:/usr/app/packages/shared-frontend-components/
      - /usr/app/packages/shared-frontend-components/node_modules
      - ./packages/shared-frontend-utilities:/usr/app/packages/shared-frontend-utilities/
      - /usr/app/packages/shared-frontend-utilities/node_modules

  frontend-e2e:
    environment:
      CYPRESS_VIDEO: "true"
      CYPRESS_SCREENSHOT_ON_RUN_FAILURE: "true"
    volumes:
      - ./packages/e2e-web:/usr/app/packages/e2e-web/
      - /usr/app/packages/e2e-web/node_modules
