version: "3.3"
services:

  postgres:
    build: ./packages/database
    container_name: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  backend-dev:
    build: .
    depends_on:
      - postgres
    environment:
      DB_CONNECTION_STRING: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3005
      DEFAULT_COUNTRY_ID: gbr
    ports:
      - "5205:3005"
    command: npm run backend:dev
    volumes:
      - ./packages/backend:/usr/app/packages/backend/
      - /usr/app/packages/backend/node_modules

  frontend-dev:
    build: .
    depends_on:
      - backend-dev
    environment:
      BACKEND_URL: http://localhost:5200/v2
    ports:
      - "5200:3000"
    command: npm run frontend:dev
    volumes:
      - ./packages/frontend:/usr/app/packages/frontend/
      - /usr/app/packages/frontend/node_modules
