version: "3.3"
services:

  postgres-test:
    build:
      context: .
      dockerfile: docker-database.Dockerfile
    container_name: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  backend-test:
    build:
      context: .
      dockerfile: docker-backend.Dockerfile
    depends_on:
      - postgres-test
    environment:
      DB_CONNECTION_STRING: postgres://user:pass@postgres:5432/db
      DEFAULT_COUNTRY_ID: gbr
    command: npm run backend:test
