version: "3.3"
services:

  seasonal-database:
    build:
      context: .
      dockerfile: docker-seasonal-database.Dockerfile
    ports:
      - "45432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  seasonal-backend:
    build:
      context: .
      dockerfile: docker-seasonal-backend.Dockerfile
    depends_on:
      - seasonal-database
    ports:
      - "5200:5200"
    environment:
      PORT: 5200
      DB_CONNECTION_STRING: postgres://user:pass@seasonal-database:5432/db
      DEFAULT_COUNTRY_ID: gbr
      IS_CI: "true"
    command: yarn workspace @chrisb-dev/seasonal-backend dev

  seasonal-frontend:
    build:
      context: .
      dockerfile: docker-seasonal-frontend.Dockerfile
    depends_on:
      - seasonal-backend
    environment:
      PORT: 5201
      REACT_APP_BACKEND_URL: http://seasonal-backend:5200/v2
    ports:
      - "5201:5201"
    command: yarn workspace @chrisb-dev/seasonal-frontend http-server

  seasonal-e2e-web:
    build:
      context: .
      dockerfile: docker-seasonal-e2e-web.Dockerfile
    depends_on:
      - seasonal-frontend
    command: yarn workspace @chrisb-dev/seasonal-e2e-web test
    environment:
      CYPRESS_BASE_URL: http://seasonal-frontend:5201
      CYPRESS_VIDEO: "false"
      CYPRESS_SCREENSHOT_ON_RUN_FAILURE: "false"
