version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.10

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
          - "20:c4:e5:4d:d2:3e:cb:47:2a:a6:e3:8c:96:5d:04:a1"

      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm i

      - run:
          name: Build dist version
          command: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: Init git
          command: |
            git config user.email "chrisberry4545@googlemail.com"
            git config user.name "ci-cb"

      - run:
          name: Deploy application
          command: npm run gh-pages

workflows:
  version: 2
  ci:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
