version: 2.1

commands:
  install-dependencies:
    steps:
      - restore_cache:
          name: Restore dependency cache
          keys:
            - seasonal-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm i
            npm run bootstrap
      - save_cache:
          name: Save dependency cache
          paths:
            - node_modules
          key: seasonal-deps-{{ checksum "package-lock.json" }}

jobs:
  backend_test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - setup_remote_docker
      - install-dependencies
      - run:
          name: Run backend tests
          command: |
            cd ./packages/backend
            ./tests/run-functional-tests.sh

  backend_deploy:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Copy env config
          command: |
            cd ./packages/backend
            cp .env-ci.yml .env.yml
      - run:
          name: Build dist version
          command: |
            cd ./packages/backend
            npm run build
            npm run move-dist-to-top-level
      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless
      - run:
          name: Deploy application
          command: |
            cd ./packages/backend
            sls deploy --stage prod

workflows:
  version: 2
  backend:
    jobs:
      - backend_test
      - backend_approval:
          type: approval
          filters:
            branches:
              only:
                - master
          requires:
           - backend_test
      - backend_deploy:
          requires:
            - backend_approval
