version: 2.1

commands:
  install-dependencies:
    steps:
      - restore_cache:
          name: Restore dependency cache
          keys:
            - seasonal-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save dependency cache
          paths:
            - node_modules
          key: seasonal-deps-{{ checksum "yarn.lock" }}

jobs:
  backend_test:
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run backend tests
          command: yarn docker:backend:test

  backend_deploy:
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Copy env config
          command: cp packages/backend/.env-ci.yml packages/backend/.env.yml
      - run:
          name: Build dist version
          command: |
            yarn workspace @chrisb-dev/seasonal-backend build
            yarn workspace @chrisb-dev/seasonal-backend move-dist-to-top-level
      - run:
          name: Install Serverless CLI
          command: sudo yarn global add serverless
      - run:
          name: Deploy backend
          command: |
            cd ./packages/backend
            sls deploy --stage prod

  frontend_deploy:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - install-dependencies
      - add_ssh_keys:
          fingerprints:
            - cd:42:e8:de:36:e3:c0:f9:0d:6f:55:27:47:57:ab:4b
      - run:
          name: Git configuration
          command: |
            git config user.email "chrisbery4545@googlemail.com"
            git config user.name "chrisbery4545"
      - run:
          name: Deploy frontend
          command: yarn frontend:deploy

  frontend_admin_deploy:
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - install-dependencies
      - add_ssh_keys:
          fingerprints:
            - 3f:1a:98:c5:19:4c:cf:92:c8:5d:f6:eb:2d:d5:37:f9
      - run:
          name: Deploy frontend admin
          command: yarn frontend-admin:deploy

workflows:
  version: 2
  backend:
    jobs:
      - backend_approval:
          type: approval
      - backend_test:
          requires:
           - backend_approval
      - backend_deploy:
          requires:
            - backend_test
      - frontend_approval:
          type: approval
      - frontend_deploy:
          requires:
            - frontend_approval
      - frontend_admin_approval:
          type: approval
      - frontend_admin_deploy:
          requires:
            - frontend_admin_approval
