import {
  ENDPOINT_V2_SEASON,
  ENDPOINT_V2_FOOD,
  ENDPOINT_V2_SEASON_WITH_FOOD,
  ENDPOINT_V2_SEASON_WITH_RECIPES,
  ENDPOINT_V2_COUNTRY,
  ENDPOINT_ADMIN_BADGE,
  ENDPOINT_ADMIN_COUNTRY,
  ENDPOINT_ADMIN_COUNTRY_FOOD_NAME_MAP,
  ENDPOINT_ADMIN_COUNTRY_RECIPE_NAME_MAP,
  ENDPOINT_ADMIN_FOOD,
  ENDPOINT_ADMIN_LOGIN,
  ENDPOINT_ADMIN_RECIPE,
  ENDPOINT_ADMIN_REGION,
  ENDPOINT_ADMIN_REGION_FOOD_SEASON_MAP,
  ENDPOINT_ADMIN_USER,
  ENDPOINT_ADMIN_REPORT_FOOD_WITH_NO_RECIPES
} from './urls';

export const serverlessUrls = () => ({
  adminBadge: ENDPOINT_ADMIN_BADGE,
  adminCountry: ENDPOINT_ADMIN_COUNTRY,
  adminCountryFoodNameMap: ENDPOINT_ADMIN_COUNTRY_FOOD_NAME_MAP,
  adminCountryRecipeNameMap: ENDPOINT_ADMIN_COUNTRY_RECIPE_NAME_MAP,
  adminFood: ENDPOINT_ADMIN_FOOD,
  adminLogin: ENDPOINT_ADMIN_LOGIN,
  adminRecipe: ENDPOINT_ADMIN_RECIPE,
  adminRegion: ENDPOINT_ADMIN_REGION,
  adminRegionFoodSeasonMap: ENDPOINT_ADMIN_REGION_FOOD_SEASON_MAP,
  adminUser: ENDPOINT_ADMIN_USER,

  adminReportFoodWithNoRecipes: ENDPOINT_ADMIN_REPORT_FOOD_WITH_NO_RECIPES,

  v2Country: ENDPOINT_V2_COUNTRY,
  v2Food: ENDPOINT_V2_FOOD,
  v2Season: ENDPOINT_V2_SEASON,
  v2SeasonWithFood: ENDPOINT_V2_SEASON_WITH_FOOD,
  v2SeasonWithRecipes: ENDPOINT_V2_SEASON_WITH_RECIPES
});
