import {
  ENDPOINT_V2,
  ENDPOINT_SEASON,
  ENDPOINT_FOOD_DETAILS,
  ENDPOINT_SEASON_WITH_FOOD,
  ENDPOINT_SEASON_WITH_RECIPES,
  ENDPOINT_BADGE,
  ENDPOINT_COUNTRY,
  ENDPOINT_ADMIN,
  ENDPOINT_COUNTRY_FOOD_NAME_MAP,
  ENDPOINT_COUNTRY_RECIPE_NAME_MAP,
  ENDPOINT_LOGIN,
  ENDPOINT_RECIPE,
  ENDPOINT_REGION,
  ENDPOINT_REGION_FOOD_SEASON_MAP,
  ENDPOINT_USER
} from '@chrisb-dev/seasonal-shared-models';

export const ENDPOINT_V2_SEASON = `${ENDPOINT_V2}/${ENDPOINT_SEASON}`;
export const ENDPOINT_V2_FOOD = `${ENDPOINT_V2}/${ENDPOINT_FOOD_DETAILS}`;
export const ENDPOINT_V2_SEASON_WITH_FOOD =
  `${ENDPOINT_V2}/${ENDPOINT_SEASON_WITH_FOOD}`;
export const ENDPOINT_V2_SEASON_WITH_RECIPES =
  `${ENDPOINT_V2}/${ENDPOINT_SEASON_WITH_RECIPES}`;
export const ENDPOINT_V2_COUNTRY =
  `${ENDPOINT_V2}/${ENDPOINT_COUNTRY}`;

export const ENDPOINT_ADMIN_BADGE = `${ENDPOINT_ADMIN}/${ENDPOINT_BADGE}`;
export const ENDPOINT_ADMIN_COUNTRY = `${ENDPOINT_ADMIN}/${ENDPOINT_COUNTRY}`;
export const ENDPOINT_ADMIN_COUNTRY_FOOD_NAME_MAP =
  `${ENDPOINT_ADMIN}/${ENDPOINT_COUNTRY_FOOD_NAME_MAP}`;
export const ENDPOINT_ADMIN_COUNTRY_RECIPE_NAME_MAP =
  `${ENDPOINT_ADMIN}/${ENDPOINT_COUNTRY_RECIPE_NAME_MAP}`;
export const ENDPOINT_ADMIN_FOOD = `${ENDPOINT_ADMIN}/${ENDPOINT_FOOD_DETAILS}`;
export const ENDPOINT_ADMIN_LOGIN = `${ENDPOINT_ADMIN}/${ENDPOINT_LOGIN}`;
export const ENDPOINT_ADMIN_RECIPE = `${ENDPOINT_ADMIN}/${ENDPOINT_RECIPE}`;
export const ENDPOINT_ADMIN_REGION = `${ENDPOINT_ADMIN}/${ENDPOINT_REGION}`;
export const ENDPOINT_ADMIN_REGION_FOOD_SEASON_MAP =
  `${ENDPOINT_ADMIN}/${ENDPOINT_REGION_FOOD_SEASON_MAP}`;
export const ENDPOINT_ADMIN_USER =
  `${ENDPOINT_ADMIN}/${ENDPOINT_USER}`;
