import {
  ENDPOINT_LOGIN,
  ENDPOINT_COUNTRY,
  ENDPOINT_COUNTRY_FOOD_NAME_MAP,
  ENDPOINT_REGION_FOOD_SEASON_MAP,
  ENDPOINT_COUNTRY_RECIPE_NAME_MAP,
  ENDPOINT_FOOD_DETAILS,
  ENDPOINT_RECIPE,
  ENDPOINT_REGION,
  ENDPOINT_USER,
  ENDPOINT_BADGE
} from '@chrisb-dev/seasonal-shared-models';

const ADMIN_BACKEND_URL = process.env.REACT_APP_ADMIN_BACKEND_URL
  || 'https://6usraevcmc.execute-api.eu-west-2.amazonaws.com/prod/admin';

export const LOGIN_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_LOGIN}`;

export const BADGE_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_BADGE}`;

export const COUNTRY_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_COUNTRY}`;

export const COUNTRY_FOOD_NAME_MAP_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_COUNTRY_FOOD_NAME_MAP}`;

export const REGION_FOOD_SEASON_MAP_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_REGION_FOOD_SEASON_MAP}`;

export const COUNTRY_RECIPE_NAME_MAP_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_COUNTRY_RECIPE_NAME_MAP}`;

export const FOOD_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_FOOD_DETAILS}`;

export const RECIPE_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_RECIPE}`;

export const REGION_URL = `${ADMIN_BACKEND_URL}/${ENDPOINT_REGION}`;

export const USER_URL =
  process.env.REACT_APP_USER_URL || `${ADMIN_BACKEND_URL}/${ENDPOINT_USER}`;
