export enum ROUTES {
  BADGES = 'badges',
  CREATE = 'create',
  COUNTRY = 'country',
  COUNTRY_FOOD_NAME_MAP = 'country-food-name-map',
  COUNTRY_RECIPE_NAME_MAP = 'country-recipe-name-map',
  EDIT = 'edit',
  FOOD = 'food',
  HOME = 'home',
  LOGIN = '',
  RECIPE = 'recipe',
  REGION = 'region',
  REGION_FOOD_SEASON_MAP = 'region-food-season-map',
  REPORTS_FOOD_MISSING_RECIPES = 'report-food-missing-recipes',
  TRANSLATIONS_BADGE_NAME = 'translations-badge-name',
  TRANSLATIONS_COUNTRY_NAME = 'translations-country-name',
  TRANSLATIONS_REGION_NAME = 'translations-region-name',
  TRANSLATIONS_SEASON_NAME = 'translations-season-name',
  USER = 'user'
}
