service: seasonal-backend

plugins:
  - serverless-plugin-monorepo

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2
  environment: ${file(.env.yml)}

functions:
  v2Food:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.v2Food}/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  v2Season:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.v2Season}
          method: get
          cors: true
  v2SeasonWithFood:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.v2SeasonWithFood}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.v2SeasonWithFood}/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  v2SeasonWithRecipes:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.v2SeasonWithRecipes}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.v2SeasonWithRecipes}/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  v2Country:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.v2Country}
          method: get
          cors: true
  adminLogin:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminLogin}
          method: post
          cors: true
  adminCountry:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountry}
          method: post
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountry}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountry}/{id}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountry}
          method: patch
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountry}/{id}
          method: delete
          cors: true
  adminCountryFoodNameMap:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryFoodNameMap}
          method: post
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryFoodNameMap}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryFoodNameMap}/{id}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryFoodNameMap}
          method: patch
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryFoodNameMap}/{id}
          method: delete
          cors: true
  adminCountryRecipeNameMap:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryRecipeNameMap}
          method: post
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryRecipeNameMap}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryRecipeNameMap}/{id}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryRecipeNameMap}
          method: patch
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminCountryRecipeNameMap}/{id}
          method: delete
          cors: true
  adminFood:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminFood}
          method: post
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminFood}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminFood}/{id}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminFood}
          method: patch
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminFood}/{id}
          method: delete
          cors: true
  adminRecipe:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRecipe}
          method: post
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRecipe}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRecipe}/{id}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRecipe}
          method: patch
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRecipe}/{id}
          method: delete
          cors: true
  adminRegion:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegion}
          method: post
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegion}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegion}/{id}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegion}
          method: patch
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegion}/{id}
          method: delete
          cors: true
  adminRegionFoodSeasonMap:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegionFoodSeasonMap}
          method: post
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegionFoodSeasonMap}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegionFoodSeasonMap}/{id}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegionFoodSeasonMap}
          method: patch
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminRegionFoodSeasonMap}/{id}
          method: delete
          cors: true
  adminUser:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminUser}
          method: post
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminUser}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminUser}/{id}
          method: get
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminUser}
          method: patch
          cors: true
      - http:
          path: ${file(./src/config/serverless-urls.js):serverlessUrls.adminUser}/{id}
          method: delete
          cors: true
