service: seasonal-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-2
  environment: ${file(.env.yml)}

functions:
  v2Food:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(.env.yml):V2_ENDPOINT}/${file(.env.yml):FOOD_ENDPOINT}/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  v2Season:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(.env.yml):V2_ENDPOINT}/${file(.env.yml):SEASON_ENDPOINT}
          method: get
          cors: true
  v2SeasonWithFood:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(.env.yml):V2_ENDPOINT}/${file(.env.yml):SEASON_WITH_FOOD_ENDPOINT}
          method: get
          cors: true
      - http:
          path: ${file(.env.yml):V2_ENDPOINT}/${file(.env.yml):SEASON_WITH_FOOD_ENDPOINT}/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  v2SeasonWithRecipes:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(.env.yml):V2_ENDPOINT}/${file(.env.yml):SEASON_WITH_RECIPES_ENDPOINT}
          method: get
          cors: true
      - http:
          path: ${file(.env.yml):V2_ENDPOINT}/${file(.env.yml):SEASON_WITH_RECIPES_ENDPOINT}/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  v2Country:
    handler: index-serverless.handler
    events:
      - http:
          path: ${file(.env.yml):V2_ENDPOINT}/${file(.env.yml):COUNTRY_ENDPOINT}
          method: get
          cors: true
  adminLogin:
    handler: index-serverless.handler
    events:
      - http:
          path: admin/login
          method: post
          cors: true
  adminCountry:
    handler: index-serverless.handler
    events:
      - http:
          path: admin/country
          method: post
          cors: true
      - http:
          path: admin/country
          method: get
          cors: true
      - http:
          path: admin/country
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: admin/country
          method: patch
          cors: true
      - http:
          path: admin/country
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
  adminFood:
    handler: index-serverless.handler
    events:
      - http:
          path: admin/food
          method: post
          cors: true
      - http:
          path: admin/food
          method: get
          cors: true
      - http:
          path: admin/food
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: admin/food
          method: patch
          cors: true
      - http:
          path: admin/food
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
  adminRecipe:
    handler: index-serverless.handler
    events:
      - http:
          path: admin/recipe
          method: post
          cors: true
      - http:
          path: admin/recipe
          method: get
          cors: true
      - http:
          path: admin/recipe
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: admin/recipe
          method: patch
          cors: true
      - http:
          path: admin/recipe
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
  adminRegion:
    handler: index-serverless.handler
    events:
      - http:
          path: admin/region
          method: post
          cors: true
      - http:
          path: admin/region
          method: get
          cors: true
      - http:
          path: admin/region
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: admin/region
          method: patch
          cors: true
      - http:
          path: admin/region
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
  adminUser:
    handler: index-serverless.handler
    events:
      - http:
          path: admin/user
          method: post
          cors: true
      - http:
          path: admin/user
          method: get
          cors: true
      - http:
          path: admin/user
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: admin/user
          method: patch
          cors: true
      - http:
          path: admin/user
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
